//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJSoftEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBAJEntities : DbContext
    {
        public DBAJEntities()
            : base("name=DBAJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FinanceSale> FinanceSales { get; set; }
        public virtual DbSet<JariCompany> JariCompanies { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ShadeCard> ShadeCards { get; set; }
        public virtual DbSet<SiteConfig> SiteConfigs { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<TranDetail> TranDetails { get; set; }
        public virtual DbSet<TranHeader> TranHeaders { get; set; }
        public virtual DbSet<TranJournal> TranJournals { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<YarnType> YarnTypes { get; set; }
        public virtual DbSet<vw_ShadeCards> vw_ShadeCards { get; set; }
        public virtual DbSet<vw_Users> vw_Users { get; set; }
        public virtual DbSet<EmbroideryFirmPriceSetting> EmbroideryFirmPriceSettings { get; set; }
        public virtual DbSet<EmbroideryFirm> EmbroideryFirms { get; set; }
        public virtual DbSet<EmbroideryFirmLocation> EmbroideryFirmLocations { get; set; }
        public virtual DbSet<vw_EmbroideryFirms> vw_EmbroideryFirms { get; set; }
        public virtual DbSet<vw_EmbroideryFirmPriceSettings> vw_EmbroideryFirmPriceSettings { get; set; }
    
        [DbFunction("DBAJEntities", "f_split")]
        public virtual IQueryable<f_split_Result> f_split(string param, string delimiter)
        {
            var paramParameter = param != null ?
                new ObjectParameter("param", param) :
                new ObjectParameter("param", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_split_Result>("[DBAJEntities].[f_split](@param, @delimiter)", paramParameter, delimiterParameter);
        }
    }
}
