//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJSoftEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPriceSetting
    {
        public int CompanyPriceSettingsId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<int> YarnTypeId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual YarnType YarnType { get; set; }
        public virtual Company Company { get; set; }
    }
}
