//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJSoftEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmbroideryFirm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmbroideryFirm()
        {
            this.EmbroideryFirmPriceSettings = new HashSet<EmbroideryFirmPriceSetting>();
            this.TranDetails = new HashSet<TranDetail>();
            this.TranHeaders = new HashSet<TranHeader>();
            this.TranJournals = new HashSet<TranJournal>();
            this.EmbroideryFirmLocations = new HashSet<EmbroideryFirmLocation>();
        }
    
        public System.Guid EmbroideryFirmId { get; set; }
        public int JariCompanyId { get; set; }
        public bool IsActive { get; set; }
        public string EmbroideryFirmName { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmbroideryFirmPriceSetting> EmbroideryFirmPriceSettings { get; set; }
        public virtual JariCompany JariCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranDetail> TranDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranHeader> TranHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranJournal> TranJournals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmbroideryFirmLocation> EmbroideryFirmLocations { get; set; }
    }
}
