//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJSoftEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShadeCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShadeCard()
        {
            this.TranDetails = new HashSet<TranDetail>();
            this.EmbroideryFirmPriceSettings = new HashSet<EmbroideryFirmPriceSetting>();
        }
    
        public int ShadeId { get; set; }
        public int JariCompanyId { get; set; }
        public int YarnTypeId { get; set; }
        public string ShadeName { get; set; }
        public byte[] ShadeImage { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual JariCompany JariCompany { get; set; }
        public virtual YarnType YarnType { get; set; }
        public virtual ShadeCard ShadeCards1 { get; set; }
        public virtual ShadeCard ShadeCard1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranDetail> TranDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmbroideryFirmPriceSetting> EmbroideryFirmPriceSettings { get; set; }
    }
}
