//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJSoftEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TranHeader()
        {
            this.TranDetails = new HashSet<TranDetail>();
            this.TranDetails1 = new HashSet<TranDetail>();
            this.TranJournals = new HashSet<TranJournal>();
        }
    
        public System.Guid TranHeaderId { get; set; }
        public int JariCompanyId { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid CompanyLocationId { get; set; }
        public string TranType { get; set; }
        public string TranSubType { get; set; }
        public string TranStatus { get; set; }
        public string TransactionId { get; set; }
        public string InvoiceNumber { get; set; }
        public string PaidBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> BillingTerms { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual JariCompany JariCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranDetail> TranDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranDetail> TranDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranJournal> TranJournals { get; set; }
        public virtual EmbroideryFirm EmbroideryFirm { get; set; }
        public virtual EmbroideryFirmLocation EmbroideryFirmLocation { get; set; }
    }
}
