//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJSoftEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranJournal
    {
        public System.Guid TranJournalId { get; set; }
        public System.Guid TranHeaderId { get; set; }
        public int JariCompanyId { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid CompanyLocationId { get; set; }
        public string Reference { get; set; }
        public string TranJournalNotes { get; set; }
        public Nullable<decimal> CR { get; set; }
        public Nullable<decimal> DR { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual JariCompany JariCompany { get; set; }
        public virtual TranHeader TranHeader { get; set; }
        public virtual EmbroideryFirm EmbroideryFirm { get; set; }
    }
}
