//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJSoftEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranDetail
    {
        public System.Guid TranDetailId { get; set; }
        public System.Guid TranHeaderId { get; set; }
        public int JariCompanyId { get; set; }
        public System.Guid CompanyId { get; set; }
        public Nullable<int> ShadeId { get; set; }
        public Nullable<System.Guid> InvoiceTranHeaderId { get; set; }
        public Nullable<decimal> TranDetailAmt { get; set; }
        public string TranDetailNotes { get; set; }
        public bool IsDiscount { get; set; }
        public bool IsPercentage { get; set; }
        public bool IsAdjustmentAmt { get; set; }
    
        public virtual JariCompany JariCompany { get; set; }
        public virtual ShadeCard ShadeCard { get; set; }
        public virtual TranHeader TranHeader { get; set; }
        public virtual TranHeader TranHeader1 { get; set; }
        public virtual EmbroideryFirm EmbroideryFirm { get; set; }
    }
}
