//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJSoftEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmbroideryFirms
    {
        public System.Guid EmbroideryFirmId { get; set; }
        public int JariCompanyId { get; set; }
        public bool IsActive { get; set; }
        public string EmbroideryFirmName { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string JariCompanyName { get; set; }
        public Nullable<int> TotalLocations { get; set; }
        public System.Guid EmbroideryFirmLocationId { get; set; }
        public string ContactPerson { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public Nullable<int> BillingTerms { get; set; }
        public string FullAddress { get; set; }
    }
}
