//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJSoftEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmbroideryFirmPriceSettings
    {
        public System.Guid EmbroideryFirmId { get; set; }
        public int ShadeId { get; set; }
        public int JariCompanyId { get; set; }
        public int YarnTypeId { get; set; }
        public string YarnTypeName { get; set; }
        public string YarnColorCode { get; set; }
        public string ShadeName { get; set; }
        public byte[] ShadeImage { get; set; }
        public string Description { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> EmbroideryFirmPriceSettingsId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> IsDefaultPrice { get; set; }
        public Nullable<long> RowNumber { get; set; }
    }
}
