//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AJSoftEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Statements
    {
        public string CompanyName { get; set; }
        public System.Guid CompanyId { get; set; }
        public decimal Crnt { get; set; }
        public decimal A1_30 { get; set; }
        public decimal A31_60 { get; set; }
        public decimal A61_90 { get; set; }
        public decimal A90 { get; set; }
        public decimal CreditBalance { get; set; }
        public Nullable<decimal> RowTotal { get; set; }
    }
}
